/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplicacion.views.gui;

import aplicacion.controllers.gui.MessageUtilsGUI;
import aplicacion.data.AlumnoData;
import aplicacion.data.ApoderadoData;
import aplicacion.data.CursoData;
import aplicacion.models.Alumno;
import aplicacion.models.Apoderado;
import aplicacion.models.Curso;
import java.awt.Color;

import java.util.List;
import javax.swing.*;
import javax.swing.event.ListDataListener;

import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 * Clase que controla la interacción con alumnso en la ejecución de la interfaz gráfica.
 *
 * @author Sebastián García, Guillermo González, Benjamín Navarrete
 * @version 3.0
 */
public class AlumnoViewGUI extends javax.swing.JPanel {
    
    private final AlumnoData alumnoData;
    private final ApoderadoData apoderadoData;
    private final CursoData cursoData;

    /**
     * Creates new form Agregar
     */
    int xMouse, yMouse;
    public AlumnoViewGUI(AlumnoData alumnoData, ApoderadoData apoderadoData, CursoData cursoData) {
        this.alumnoData = alumnoData;
        this.apoderadoData = apoderadoData;
        this.cursoData = cursoData;
        initComponents();
    }
    
    private DefaultComboBoxModel getCursosCB() {
        
        List<Curso> cursos = this.cursoData.getCursos();
        String labels[] = new String[cursos.size()];
        int i = 0;
        for (Curso curso: cursos) {
            labels[i] = curso.cursoToString();
            i++;
        }
        return new DefaultComboBoxModel(labels);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rutAlumnoTextField = new javax.swing.JTextField();
        nombresAlumnoTextField = new javax.swing.JTextField();
        apPatTextField = new javax.swing.JTextField();
        apMatTextField = new javax.swing.JTextField();
        rutApoderadoTextField = new javax.swing.JTextField();
        nombresApoderadoTextField = new javax.swing.JTextField();
        apPatApTextField = new javax.swing.JTextField();
        apMatApTextField = new javax.swing.JTextField();
        emailApTextField = new javax.swing.JTextField();
        telefonoApTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 239, 240));

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 142, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar un nuevo alumno");

        rutAlumnoTextField.setBackground(new java.awt.Color(250, 250, 250));
        rutAlumnoTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        rutAlumnoTextField.setForeground(new java.awt.Color(35, 33, 35));
        rutAlumnoTextField.setText("RUT alumno");
        rutAlumnoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rutAlumnoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rutAlumnoTextFieldFocusLost(evt);
            }
        });

        nombresAlumnoTextField.setBackground(new java.awt.Color(250, 250, 250));
        nombresAlumnoTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        nombresAlumnoTextField.setForeground(new java.awt.Color(35, 33, 35));
        nombresAlumnoTextField.setText("Nombres alumno");
        nombresAlumnoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombresAlumnoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombresAlumnoTextFieldFocusLost(evt);
            }
        });

        apPatTextField.setBackground(new java.awt.Color(250, 250, 250));
        apPatTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        apPatTextField.setForeground(new java.awt.Color(35, 33, 35));
        apPatTextField.setText("Apellido paterno alumno");
        apPatTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apPatTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apPatTextFieldFocusLost(evt);
            }
        });

        apMatTextField.setBackground(new java.awt.Color(250, 250, 250));
        apMatTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        apMatTextField.setForeground(new java.awt.Color(35, 33, 35));
        apMatTextField.setText("Apellido materno alumno");
        apMatTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apMatTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apMatTextFieldFocusLost(evt);
            }
        });

        rutApoderadoTextField.setBackground(new java.awt.Color(250, 250, 250));
        rutApoderadoTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        rutApoderadoTextField.setForeground(new java.awt.Color(35, 33, 35));
        rutApoderadoTextField.setText("RUT Apoderado");
        rutApoderadoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rutApoderadoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rutApoderadoTextFieldFocusLost(evt);
            }
        });

        nombresApoderadoTextField.setBackground(new java.awt.Color(250, 250, 250));
        nombresApoderadoTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        nombresApoderadoTextField.setForeground(new java.awt.Color(35, 33, 35));
        nombresApoderadoTextField.setText("Nombres apoderado");
        nombresApoderadoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombresApoderadoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombresApoderadoTextFieldFocusLost(evt);
            }
        });

        apPatApTextField.setBackground(new java.awt.Color(250, 250, 250));
        apPatApTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        apPatApTextField.setForeground(new java.awt.Color(35, 33, 35));
        apPatApTextField.setText("Apellido paterno apoderado");
        apPatApTextField.setToolTipText("");
        apPatApTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apPatApTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apPatApTextFieldFocusLost(evt);
            }
        });

        apMatApTextField.setBackground(new java.awt.Color(250, 250, 250));
        apMatApTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        apMatApTextField.setForeground(new java.awt.Color(35, 33, 35));
        apMatApTextField.setText("Apellido materno apoderado");
        apMatApTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apMatApTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apMatApTextFieldFocusLost(evt);
            }
        });

        emailApTextField.setBackground(new java.awt.Color(250, 250, 250));
        emailApTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        emailApTextField.setForeground(new java.awt.Color(35, 33, 35));
        emailApTextField.setText("Correo electrónico apoderado");
        emailApTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailApTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailApTextFieldFocusLost(evt);
            }
        });

        telefonoApTextField.setBackground(new java.awt.Color(250, 250, 250));
        telefonoApTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        telefonoApTextField.setForeground(new java.awt.Color(35, 33, 35));
        telefonoApTextField.setText("Teléfono apoderado");
        telefonoApTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonoApTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoApTextFieldFocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 142, 153));
        jButton1.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(250, 250, 250));
        jButton1.setIcon(saveIcon());
        jButton1.setText("Guardar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(250, 250, 250));
        jComboBox1.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(35, 33, 35));
        jComboBox1.setModel(this.getCursosCB());

        jLabel13.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 142, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Datos alumno");

        jLabel14.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 142, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Datos apoderado");

        jLabel15.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 142, 153));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Curso del alumno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apPatTextField)
                            .addComponent(apMatTextField)
                            .addComponent(rutAlumnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombresAlumnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rutApoderadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(telefonoApTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailApTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(apMatApTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(apPatApTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombresApoderadoTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(rutAlumnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombresAlumnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apPatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apMatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(rutApoderadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombresApoderadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apPatApTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apMatApTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailApTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoApTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Permite obtener las coordenadas del mouse.
     *
     * @param evt Evento.
     */
    private void headerMousePressed(java.awt.event.MouseEvent evt) {                                    
        xMouse = evt.getX();
        yMouse = evt.getY();
    }
    
    private Icon saveIcon() {
        return IconFontSwing.buildIcon(FontAwesome.FLOPPY_O, 25, new Color(250, 250, 250));
    }


    /**
     * Permite agregar un alumno al sistema
     *
     * @param evt Evento.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Curso curso = null;
        for (Curso c: cursoData.getCursos()) {
            if (c != null && c.cursoToString().equals(jComboBox1.getSelectedItem().toString())) {
                curso = c;
            }
        }
        
        if (curso != null) {

            Apoderado apoderado = new Apoderado(
                    rutApoderadoTextField.getText(),
                    nombresApoderadoTextField.getText(),
                    apPatApTextField.getText(),
                    apMatApTextField.getText(),
                    Integer.parseInt(telefonoApTextField.getText()),
                    emailApTextField.getText()
            );
            Alumno alumno = new Alumno(
                    rutAlumnoTextField.getText(),
                    nombresAlumnoTextField.getText(),
                    apPatTextField.getText(),
                    apMatTextField.getText(),
                    curso.getNivel(),
                    curso.getParalelo(),
                    apoderado
            );
            this.apoderadoData.insertApoderado(apoderado);
            this.alumnoData.insertAlumno(alumno);
            MessageUtilsGUI.infoMsg("El alumno ha sido agregado con éxito");
        } else {
            MessageUtilsGUI.errorMsg("No ha seleccionado un curso.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rutAlumnoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutAlumnoTextFieldFocusGained
        // TODO add your handling code here:
        rutAlumnoTextField.setText("");
    }//GEN-LAST:event_rutAlumnoTextFieldFocusGained

    private void rutAlumnoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutAlumnoTextFieldFocusLost
        // TODO add your handling code here:
        if (rutAlumnoTextField.getText().equals("")) rutAlumnoTextField.setText("RUT alumno");
    }//GEN-LAST:event_rutAlumnoTextFieldFocusLost

    private void nombresAlumnoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresAlumnoTextFieldFocusGained
        // TODO add your handling code here:
        nombresAlumnoTextField.setText("");
        
    }//GEN-LAST:event_nombresAlumnoTextFieldFocusGained

    private void nombresAlumnoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresAlumnoTextFieldFocusLost
        // TODO add your handling code here:
        if (nombresAlumnoTextField.getText().equals("")) nombresAlumnoTextField.setText("Nombres alumno");
    }//GEN-LAST:event_nombresAlumnoTextFieldFocusLost

    private void apPatTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apPatTextFieldFocusGained
        // TODO add your handling code here:
        apPatTextField.setText("");
    }//GEN-LAST:event_apPatTextFieldFocusGained

    private void apPatTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apPatTextFieldFocusLost
        // TODO add your handling code here:
        if (apPatTextField.getText().equals("")) apPatTextField.setText("Apellido paterno alumno");
    }//GEN-LAST:event_apPatTextFieldFocusLost

    private void apMatTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apMatTextFieldFocusGained
        // TODO add your handling code here:
        apMatTextField.setText("");
    }//GEN-LAST:event_apMatTextFieldFocusGained

    private void apMatTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apMatTextFieldFocusLost
        // TODO add your handling code here:
        if (apMatTextField.getText().equals("")) apMatTextField.setText("Apellido materno alumno");
    }//GEN-LAST:event_apMatTextFieldFocusLost

    private void rutApoderadoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutApoderadoTextFieldFocusGained
        // TODO add your handling code here:
        rutApoderadoTextField.setText("");
    }//GEN-LAST:event_rutApoderadoTextFieldFocusGained

    private void rutApoderadoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutApoderadoTextFieldFocusLost
        // TODO add your handling code here:
        if (rutApoderadoTextField.getText().equals("")) rutApoderadoTextField.setText("RUT apoderado");
    }//GEN-LAST:event_rutApoderadoTextFieldFocusLost

    private void nombresApoderadoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresApoderadoTextFieldFocusGained
        // TODO add your handling code here:
        nombresApoderadoTextField.setText("");
    }//GEN-LAST:event_nombresApoderadoTextFieldFocusGained

    private void nombresApoderadoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresApoderadoTextFieldFocusLost
        // TODO add your handling code here:
        if (nombresApoderadoTextField.getText().equals("")) nombresApoderadoTextField.setText("Nombres apoderado");
    }//GEN-LAST:event_nombresApoderadoTextFieldFocusLost

    private void apPatApTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apPatApTextFieldFocusGained
        // TODO add your handling code here:
        apPatApTextField.setText("");
    }//GEN-LAST:event_apPatApTextFieldFocusGained

    private void apPatApTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apPatApTextFieldFocusLost
        // TODO add your handling code here:
        if (apPatApTextField.getText().equals("")) apPatApTextField.setText("Apellido paterno apoderado");
    }//GEN-LAST:event_apPatApTextFieldFocusLost

    private void apMatApTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apMatApTextFieldFocusGained
        // TODO add your handling code here:
        apMatApTextField.setText("");
    }//GEN-LAST:event_apMatApTextFieldFocusGained

    private void apMatApTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apMatApTextFieldFocusLost
        // TODO add your handling code here:
        if (apMatApTextField.getText().equals("")) apMatApTextField.setText("Apellido materno apoderado");
    }//GEN-LAST:event_apMatApTextFieldFocusLost

    private void emailApTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailApTextFieldFocusGained
        // TODO add your handling code here:
        emailApTextField.setText("");
    }//GEN-LAST:event_emailApTextFieldFocusGained

    private void emailApTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailApTextFieldFocusLost
        // TODO add your handling code here:
        if (emailApTextField.getText().equals("")) emailApTextField.setText("Email apoderado");
    }//GEN-LAST:event_emailApTextFieldFocusLost

    private void telefonoApTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoApTextFieldFocusGained
        // TODO add your handling code here:
        telefonoApTextField.setText("");
    }//GEN-LAST:event_telefonoApTextFieldFocusGained

    private void telefonoApTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoApTextFieldFocusLost
        // TODO add your handling code here:
        int telefono;
        if (!telefonoApTextField.getText().equals("")) {
            try {
                telefono = Integer.parseInt(telefonoApTextField.getText());
            } catch (NumberFormatException e) {
                MessageUtilsGUI.errorMsg("El formato del teléfono debe ser numérico.");
                telefonoApTextField.setText("Teléfono apoderado");
                return;
            }
        }
        if (telefonoApTextField.getText().equals(""))
            telefonoApTextField.setText("Teléfono apoderado");
    }//GEN-LAST:event_telefonoApTextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apMatApTextField;
    private javax.swing.JTextField apMatTextField;
    private javax.swing.JTextField apPatApTextField;
    private javax.swing.JTextField apPatTextField;
    private javax.swing.JTextField emailApTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JTextField nombresAlumnoTextField;
    private javax.swing.JTextField nombresApoderadoTextField;
    private javax.swing.JTextField rutAlumnoTextField;
    private javax.swing.JTextField rutApoderadoTextField;
    private javax.swing.JTextField telefonoApTextField;
    // End of variables declaration//GEN-END:variables
}
