/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplicacion.views.gui;

import aplicacion.controllers.gui.CustomColors;
import aplicacion.controllers.gui.UtilsGUI;
import aplicacion.data.AlumnoData;
import aplicacion.data.ApoderadoData;
import aplicacion.models.Alumno;
import aplicacion.models.Apoderado;
import aplicacion.models.Curso;
import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 * Clase que controla la interacción con alumnso en la ejecución de la interfaz gráfica.
 *
 * @author Sebastián García, Guillermo González, Benjamín Navarrete
 * @version 3.0
 */
public class AlumnoViewGUI extends javax.swing.JPanel {

    private final AlumnoData alumnoData;
    private final ApoderadoData apoderadoData;
    private final List<Curso> cursoData;

    private final ShowPanelGUI bg;

    /**
     * Creates new form Agregar
     */
    int xMouse, yMouse;

    public AlumnoViewGUI(AlumnoData alumnoData, ApoderadoData apoderadoData, List<Curso> cursoData, ShowPanelGUI bg) {
        this.alumnoData = alumnoData;
        this.apoderadoData = apoderadoData;
        this.cursoData = cursoData;
        this.bg = bg;
        initComponents();
        this.rutAlumnoTextField.setEnabled(false);
        this.rutApoderadoTextField.setEnabled(false);
        this.nombresApoderadoTextField.setEnabled(false);
        this.nombresAlumnoTextField.setEnabled(false);
        this.apMatApTextField.setEnabled(false);
        this.apMatTextField.setEnabled(false);
        this.apPatApTextField.setEnabled(false);
        this.apPatTextField.setEnabled(false);
        this.telefonoApTextField.setEnabled(false);
        this.emailApTextField.setEnabled(false);
    }
    
    private DefaultComboBoxModel getCursosCB() {
        String labels[] = new String[this.cursoData.size()];
        int i = 0;
        for (Curso curso : this.cursoData) {
            labels[i] = curso.cursoToString();
            i++;
        }
        return new DefaultComboBoxModel(labels);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rutAlumnoTextField = new javax.swing.JTextField();
        nombresAlumnoTextField = new javax.swing.JTextField();
        apPatTextField = new javax.swing.JTextField();
        apMatTextField = new javax.swing.JTextField();
        rutApoderadoTextField = new javax.swing.JTextField();
        nombresApoderadoTextField = new javax.swing.JTextField();
        apPatApTextField = new javax.swing.JTextField();
        apMatApTextField = new javax.swing.JTextField();
        emailApTextField = new javax.swing.JTextField();
        telefonoApTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setForeground(null);
        setMaximumSize(new java.awt.Dimension(875, 480));
        setMinimumSize(new java.awt.Dimension(875, 480));
        setPreferredSize(new java.awt.Dimension(875, 480));
        setSize(new java.awt.Dimension(875, 480));

        rutAlumnoTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        rutAlumnoTextField.setText("RUT alumno");
        rutAlumnoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rutAlumnoTextFieldFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                rutAlumnoTextFieldFocusLost(evt);
            }
        });

        nombresAlumnoTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        nombresAlumnoTextField.setText("Nombres alumno");
        nombresAlumnoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombresAlumnoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombresAlumnoTextFieldFocusLost(evt);
            }
        });

        apPatTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        apPatTextField.setText("Apellido paterno alumno");
        apPatTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apPatTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apPatTextFieldFocusLost(evt);
            }
        });

        apMatTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        apMatTextField.setText("Apellido materno alumno");
        apMatTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apMatTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apMatTextFieldFocusLost(evt);
            }
        });

        rutApoderadoTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        rutApoderadoTextField.setText("RUT Apoderado");
        rutApoderadoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rutApoderadoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rutApoderadoTextFieldFocusLost(evt);
            }
        });

        nombresApoderadoTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        nombresApoderadoTextField.setText("Nombres apoderado");
        nombresApoderadoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombresApoderadoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombresApoderadoTextFieldFocusLost(evt);
            }
        });

        apPatApTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        apPatApTextField.setText("Apellido paterno apoderado");
        apPatApTextField.setToolTipText("");
        apPatApTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apPatApTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apPatApTextFieldFocusLost(evt);
            }
        });

        apMatApTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        apMatApTextField.setText("Apellido materno apoderado");
        apMatApTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apMatApTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apMatApTextFieldFocusLost(evt);
            }
        });

        emailApTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        emailApTextField.setText("Correo electrónico apoderado");
        emailApTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailApTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailApTextFieldFocusLost(evt);
            }
        });

        telefonoApTextField.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        telefonoApTextField.setText("Teléfono apoderado");
        telefonoApTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonoApTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoApTextFieldFocusLost(evt);
            }
        });

        jButton1.setBackground(CustomColors.MAIN_COLOR.getColor());
        jButton1.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jButton1.setForeground(CustomColors.LIGHT_COLOR.getColor());
        jButton1.setIcon(saveIcon());
        jButton1.setText("Guardar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        jComboBox1.setModel(this.getCursosCB());
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Datos alumno");

        jLabel14.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Datos apoderado");

        jLabel15.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Curso del alumno");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(144, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(374, 374, 374))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(apPatTextField)
                                                        .addComponent(apMatTextField)
                                                        .addComponent(rutAlumnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(nombresAlumnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(86, 86, 86)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rutApoderadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(telefonoApTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(emailApTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(apMatApTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(apPatApTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(nombresApoderadoTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(rutAlumnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nombresAlumnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(apPatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(apMatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rutApoderadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nombresApoderadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(apPatApTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(apMatApTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(emailApTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(telefonoApTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Permite obtener las coordenadas del mouse.
     *
     * @param evt Evento.
     */
    private void headerMousePressed(java.awt.event.MouseEvent evt) {                                    
        xMouse = evt.getX();
        yMouse = evt.getY();
    }
    
    private Icon saveIcon() {
        return IconFontSwing.buildIcon(FontAwesome.FLOPPY_O, 25, new Color(250, 250, 250));
    }


    /**
     * Permite agregar un alumno al sistema
     *
     * @param evt Evento.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Curso curso = null;
        for (Curso c : this.cursoData) {
            if (c != null && c.cursoToString().equals(jComboBox1.getSelectedItem().toString())) {
                curso = c;
            }
        }
        
        if (curso != null) {

            Apoderado apoderado = new Apoderado(
                    rutApoderadoTextField.getText(),
                    nombresApoderadoTextField.getText(),
                    apPatApTextField.getText(),
                    apMatApTextField.getText(),
                    Integer.parseInt(telefonoApTextField.getText()),
                    emailApTextField.getText()
            );
            Alumno alumno = new Alumno(
                    rutAlumnoTextField.getText(),
                    nombresAlumnoTextField.getText(),
                    apPatTextField.getText(),
                    apMatTextField.getText(),
                    curso.getNivel(),
                    curso.getParalelo(),
                    apoderado
            );
            this.apoderadoData.insertApoderado(apoderado);
            this.alumnoData.insertAlumno(alumno);
            UtilsGUI.infoMsg("El alumno ha sido agregado con éxito");
        } else {
            UtilsGUI.errorMsg("No ha seleccionado un curso.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rutAlumnoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutAlumnoTextFieldFocusGained
        // TODO add your handling code here:
        rutAlumnoTextField.setText("");
    }//GEN-LAST:event_rutAlumnoTextFieldFocusGained

    private void rutAlumnoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutAlumnoTextFieldFocusLost
        // TODO add your handling code here:
        if (rutAlumnoTextField.getText().equals("")) rutAlumnoTextField.setText("RUT alumno");
    }//GEN-LAST:event_rutAlumnoTextFieldFocusLost

    private void nombresAlumnoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresAlumnoTextFieldFocusGained
        // TODO add your handling code here:
        nombresAlumnoTextField.setText("");
        
    }//GEN-LAST:event_nombresAlumnoTextFieldFocusGained

    private void nombresAlumnoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresAlumnoTextFieldFocusLost
        // TODO add your handling code here:
        if (nombresAlumnoTextField.getText().equals("")) nombresAlumnoTextField.setText("Nombres alumno");
    }//GEN-LAST:event_nombresAlumnoTextFieldFocusLost

    private void apPatTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apPatTextFieldFocusGained
        // TODO add your handling code here:
        apPatTextField.setText("");
    }//GEN-LAST:event_apPatTextFieldFocusGained

    private void apPatTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apPatTextFieldFocusLost
        // TODO add your handling code here:
        if (apPatTextField.getText().equals("")) apPatTextField.setText("Apellido paterno alumno");
    }//GEN-LAST:event_apPatTextFieldFocusLost

    private void apMatTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apMatTextFieldFocusGained
        // TODO add your handling code here:
        apMatTextField.setText("");
    }//GEN-LAST:event_apMatTextFieldFocusGained

    private void apMatTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apMatTextFieldFocusLost
        // TODO add your handling code here:
        if (apMatTextField.getText().equals("")) apMatTextField.setText("Apellido materno alumno");
    }//GEN-LAST:event_apMatTextFieldFocusLost

    private void rutApoderadoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutApoderadoTextFieldFocusGained
        // TODO add your handling code here:
        rutApoderadoTextField.setText("");
    }//GEN-LAST:event_rutApoderadoTextFieldFocusGained

    private void rutApoderadoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutApoderadoTextFieldFocusLost
        // TODO add your handling code here:
        if (rutApoderadoTextField.getText().equals("")) rutApoderadoTextField.setText("RUT apoderado");
    }//GEN-LAST:event_rutApoderadoTextFieldFocusLost

    private void nombresApoderadoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresApoderadoTextFieldFocusGained
        // TODO add your handling code here:
        nombresApoderadoTextField.setText("");
    }//GEN-LAST:event_nombresApoderadoTextFieldFocusGained

    private void nombresApoderadoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombresApoderadoTextFieldFocusLost
        // TODO add your handling code here:
        if (nombresApoderadoTextField.getText().equals("")) nombresApoderadoTextField.setText("Nombres apoderado");
    }//GEN-LAST:event_nombresApoderadoTextFieldFocusLost

    private void apPatApTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apPatApTextFieldFocusGained
        // TODO add your handling code here:
        apPatApTextField.setText("");
    }//GEN-LAST:event_apPatApTextFieldFocusGained

    private void apPatApTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apPatApTextFieldFocusLost
        // TODO add your handling code here:
        if (apPatApTextField.getText().equals("")) apPatApTextField.setText("Apellido paterno apoderado");
    }//GEN-LAST:event_apPatApTextFieldFocusLost

    private void apMatApTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apMatApTextFieldFocusGained
        // TODO add your handling code here:
        apMatApTextField.setText("");
    }//GEN-LAST:event_apMatApTextFieldFocusGained

    private void apMatApTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apMatApTextFieldFocusLost
        // TODO add your handling code here:
        if (apMatApTextField.getText().equals("")) apMatApTextField.setText("Apellido materno apoderado");
    }//GEN-LAST:event_apMatApTextFieldFocusLost

    private void emailApTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailApTextFieldFocusGained
        // TODO add your handling code here:
        emailApTextField.setText("");
    }//GEN-LAST:event_emailApTextFieldFocusGained

    private void emailApTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailApTextFieldFocusLost
        // TODO add your handling code here:
        if (emailApTextField.getText().equals("")) emailApTextField.setText("Email apoderado");
    }//GEN-LAST:event_emailApTextFieldFocusLost

    private void telefonoApTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoApTextFieldFocusGained
        // TODO add your handling code here:
        telefonoApTextField.setText("");
    }//GEN-LAST:event_telefonoApTextFieldFocusGained

    private void telefonoApTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoApTextFieldFocusLost
        // TODO add your handling code here:
        int telefono;
        if (!telefonoApTextField.getText().equals("")) {
            try {
                telefono = Integer.parseInt(telefonoApTextField.getText());
            } catch (NumberFormatException e) {
                UtilsGUI.errorMsg("El formato del teléfono debe ser numérico.");
                telefonoApTextField.setText("Teléfono apoderado");
                return;
            }
        }
        if (telefonoApTextField.getText().equals(""))
            telefonoApTextField.setText("Teléfono apoderado");
    }//GEN-LAST:event_telefonoApTextFieldFocusLost

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        this.bg.setSubtitle("Agregando alumno al " + this.jComboBox1.getSelectedItem().toString());
        this.rutAlumnoTextField.setEnabled(true);
        this.rutApoderadoTextField.setEnabled(true);
        this.nombresApoderadoTextField.setEnabled(true);
        this.nombresAlumnoTextField.setEnabled(true);
        this.apMatApTextField.setEnabled(true);
        this.apMatTextField.setEnabled(true);
        this.apPatApTextField.setEnabled(true);
        this.apPatTextField.setEnabled(true);
        this.telefonoApTextField.setEnabled(true);
        this.emailApTextField.setEnabled(true);
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apMatApTextField;
    private javax.swing.JTextField apMatTextField;
    private javax.swing.JTextField apPatApTextField;
    private javax.swing.JTextField apPatTextField;
    private javax.swing.JTextField emailApTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JTextField nombresAlumnoTextField;
    private javax.swing.JTextField nombresApoderadoTextField;
    private javax.swing.JTextField rutAlumnoTextField;
    private javax.swing.JTextField rutApoderadoTextField;
    private javax.swing.JTextField telefonoApTextField;
    // End of variables declaration//GEN-END:variables
}
