/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplicacion.views.gui;

import aplicacion.controllers.gui.CustomColors;
import aplicacion.controllers.gui.UtilsGUI;
import aplicacion.data.AlumnoData;
import aplicacion.data.ApoderadoData;
import aplicacion.data.ProfesorData;
import aplicacion.models.Persona;
import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.awt.*;

/**
 * Clase que controla la interacción con la búsqueda de una persona en la ejecución de la interfaz gráfica.
 *
 * @author Sebastián García, Guillermo González, Benjamín Navarrete
 * @version 3.0
 */
public class BuscarViewGUI extends javax.swing.JPanel {

    private final AlumnoData alumnoData;
    private final ApoderadoData apoderadoData;
    private final ProfesorData profesorData;
    private final ShowPanelGUI bg;

    /**
     * Creates new form Buscar
     */
    public BuscarViewGUI(AlumnoData alumnoData, ApoderadoData apoderadoData, ProfesorData profesorData,
                         ShowPanelGUI bg) {
        this.alumnoData = alumnoData;
        this.apoderadoData = apoderadoData;
        this.profesorData = profesorData;
        this.bg = bg;
        initComponents();
    }
    
    private Icon eyeIcon() {
        return IconFontSwing.buildIcon(FontAwesome.SEARCH, 18, new Color(250, 250, 250));
    }

    /**
     * Permite buscar a la persona en los registros.
     *
     * @param rut RUT de la persona a buscar.
     * @return Matriz de Object con los datos a mostrar en la JTable.
     */
    private Object[][] buscarPersona(String rut) {
        Persona persona = null;
        String tipo = "";
        if (alumnoData.getAlumno(rut) != null) {
            tipo = "Alumno";
            persona = alumnoData.getAlumno(rut);
        } else if (apoderadoData.getApoderado(rut) != null) {
            tipo = "Apoderado";
            persona = apoderadoData.getApoderado(rut);
        } else if (profesorData.getProfesor(rut) != null) {
            tipo = "Profesor";
            persona = profesorData.getProfesor(rut);
        }
        if (persona != null) {
            this.bg.setSubtitle("Persona encontrada con RUT " + rut);
            return new Object[][]{{
                    persona.getRut(),
                    persona.getNombres(),
                    persona.getApMaterno(),
                    persona.getApMaterno(),
                    tipo
            }};
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(875, 480));
        setMinimumSize(new java.awt.Dimension(875, 480));
        setSize(new java.awt.Dimension(875, 480));

        jLabel1.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel1.setText("Ingrese rut de persona");

        jTextField1.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N

        jScrollPane1.setMaximumSize(new java.awt.Dimension(450, 400));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(450, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 400));
        jScrollPane1.setSize(new java.awt.Dimension(450, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null},
                },
                new String[]{
                        "rut", "Nombres", "Apellido Paterno", "Apellido materno", "Tipo"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(CustomColors.MAIN_COLOR.getColor());
        jButton1.setFont(new java.awt.Font("Fira Sans", 1, 12)); // NOI18N
        jButton1.setForeground(CustomColors.LIGHT_COLOR.getColor());
        jButton1.setIcon(eyeIcon());
        jButton1.setText("Buscar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] columns = new String[] {
                "RUT", "Nombres", "Apellido Paterno", "Apellido materno", "Tipo"
        };
        Object[][] data = buscarPersona(jTextField1.getText());
        if (data == null) {
            this.bg.setSubtitle("No se encontró persona con RUT " + jTextField1.getText());
            UtilsGUI.errorMsg("La persona con el RUT " + jTextField1.getText() + " no fue encontrada en nuestros registros.");
            return;
        }
        jTable1.setModel(new AbstractTableModel() {
            @Override
            public String getColumnName(int col) {
                return columns[col];
            }

            @Override
            public int getRowCount() {
                return data.length;
            }

            @Override
            public int getColumnCount() {
                return columns.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                return data[rowIndex][columnIndex];
            }
        });

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
