/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacion.views.gui;

import aplicacion.controllers.gui.CustomColors;
import aplicacion.controllers.gui.ReportesControllerGUI;
import aplicacion.controllers.gui.UtilsGUI;
import aplicacion.data.AlumnoData;
import aplicacion.data.ApoderadoData;
import aplicacion.data.CursoData;
import aplicacion.data.ProfesorData;
import aplicacion.data.database.*;
import aplicacion.data.datafile.AlumnoDF;
import aplicacion.data.datafile.ApoderadoDF;
import aplicacion.data.datafile.CursoDF;
import aplicacion.data.datafile.ProfesorDF;
import aplicacion.models.Alumno;
import aplicacion.models.Curso;
import aplicacion.models.Profesor;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * Clase que controla la ejecución de la interfaz gráfica.
 *
 * @author Sebastián García, Guillermo González, Benjamín Navarrete
 * @version 3.0
 */
public class GUI extends javax.swing.JFrame {

    private Map<String, Alumno> alumnosMap;
    private AlumnoData alumnoData;
    private ApoderadoData apoderadoData;
    private List<Profesor> profesoresList;
    private ProfesorData profesorData;
    private List<Curso> cursosList;
    private CursoData cursoData;

    private boolean darkMode = false;

    /**
     * Genera la interfaz gráfica.
     */
    public GUI() {
        initComponents();
        setDataType();
        this.setLocationRelativeTo(null);
        fecha.setText(UtilsGUI.getActualDate());
        this.mainPanel.setActualPanel(new InicioViewGUI(), "Bienvenidos");
    }

    private void setColorMode() {
        Color color;
        if (this.darkMode) {
            FlatArcDarkOrangeIJTheme.setup();
            color = CustomColors.LIGHT_COLOR.getColor();
        } else {
            FlatArcOrangeIJTheme.setup();
            color = CustomColors.DARK_COLOR.getColor();
        }
        this.menuBar.setForeground(color);
        this.modoOscuroMenuItem.setForeground(color);
        this.salirMenuItem.setForeground(color);
        this.repListaCursoMenuItem.setForeground(color);
        this.archivoMenu.setIcon(UtilsGUI.getIcon(FontAwesome.HOME, 12, color));
        this.reportesMenu.setIcon(UtilsGUI.getIcon(FontAwesome.FILE_ARCHIVE_O, 12, color));
        this.salirMenuItem.setIcon(UtilsGUI.getIcon(FontAwesome.SIGN_OUT, 12, color));
        this.repListaCursoMenuItem.setIcon(UtilsGUI.getIcon(FontAwesome.FILE_EXCEL_O, 12, color));
    }

    private void setDataType() {
        if (DBConnection.connect() != null) {
            UtilsGUI.infoMsg("La conexión con la base de datos fue exitosa.");
            this.alumnoData = new AlumnoDB();
            this.apoderadoData = new ApoderadoDB();
            this.profesorData = new ProfesorDB();
            this.cursoData = new CursoDB();
        } else {
            UtilsGUI.errorMsg("La conexión con la base de datos no pudo realizarse. Se utilizarán los datos locales.");
            this.alumnoData = new AlumnoDF();
            this.apoderadoData = new ApoderadoDF();
            this.profesorData = new ProfesorDF();
            this.cursoData = new CursoDF();
        }
        this.alumnosMap = this.alumnoData.getAlumnos();
        this.profesoresList = this.profesorData.getProfesores();
        this.cursosList = this.cursoData.getCursos();
    }
//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        guiPanel = new javax.swing.JPanel();
        mainTitleLbl = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        btAgregar = new javax.swing.JButton();
        btMostrarLista = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        mainPanel = new aplicacion.views.gui.ShowPanelGUI();
        btSalir = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        modoOscuroMenuItem = new javax.swing.JCheckBoxMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();
        reportesMenu = new javax.swing.JMenu();
        repListaCursoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(150, 150));
        setMaximumSize(new java.awt.Dimension(1150, 685));
        setMinimumSize(new java.awt.Dimension(1150, 685));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1150, 685));

        guiPanel.setForeground(new java.awt.Color(24, 21, 27));
        guiPanel.setMaximumSize(new java.awt.Dimension(1150, 700));
        guiPanel.setMinimumSize(new java.awt.Dimension(1150, 700));
        guiPanel.setPreferredSize(new java.awt.Dimension(1150, 700));

        mainTitleLbl.setFont(new java.awt.Font("Fira Sans", 1, 36)); // NOI18N
        mainTitleLbl.setForeground(CustomColors.MAIN_COLOR.getColor());
        mainTitleLbl.setText("Sistema de registro de asistencia");

        fecha.setFont(new java.awt.Font("Fira Sans", 2, 16)); // NOI18N
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fecha.setToolTipText("");
        fecha.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fecha.setMaximumSize(new java.awt.Dimension(300, 20));
        fecha.setMinimumSize(new java.awt.Dimension(300, 20));
        fecha.setPreferredSize(new java.awt.Dimension(300, 20));
        fecha.setSize(new java.awt.Dimension(300, 20));

        menuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(CustomColors.MAIN_COLOR.getColor(), 2, true), "  Menú  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Fira Sans", 0, 18), CustomColors.MAIN_COLOR.getColor())); // NOI18N
        menuPanel.setMaximumSize(new java.awt.Dimension(230, 575));
        menuPanel.setMinimumSize(new java.awt.Dimension(230, 575));
        menuPanel.setPreferredSize(new java.awt.Dimension(230, 575));
        menuPanel.setSize(new java.awt.Dimension(230, 575));

        btAgregar.setBackground(CustomColors.MAIN_COLOR.getColor());
        btAgregar.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        btAgregar.setForeground(CustomColors.LIGHT_COLOR.getColor());
        btAgregar.setIcon(UtilsGUI.getIcon(FontAwesome.PLUS_CIRCLE, 20, CustomColors.LIGHT_COLOR.getColor())
        );
        btAgregar.setText("Agregar alumno");
        btAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btAgregar.setIconTextGap(10);
        btAgregar.setLocation(new java.awt.Point(2, 0));
        btAgregar.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });

        btMostrarLista.setBackground(CustomColors.MAIN_COLOR.getColor());
        btMostrarLista.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        btMostrarLista.setForeground(CustomColors.LIGHT_COLOR.getColor());
        btMostrarLista.setIcon(UtilsGUI.getIcon(FontAwesome.LIST, 20, CustomColors.LIGHT_COLOR.getColor()));
        btMostrarLista.setText("Mostrar lista");
        btMostrarLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMostrarLista.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btMostrarLista.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btMostrarLista.setIconTextGap(10);
        btMostrarLista.setMargin(new java.awt.Insets(0, 20, 0, 20));
        btMostrarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarListaActionPerformed(evt);
            }
        });

        btBuscar.setBackground(CustomColors.MAIN_COLOR.getColor());
        btBuscar.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        btBuscar.setForeground(CustomColors.LIGHT_COLOR.getColor());
        btBuscar.setIcon(UtilsGUI.getIcon(FontAwesome.SEARCH, 20, CustomColors.LIGHT_COLOR.getColor()));
        btBuscar.setText("Buscar");
        btBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btBuscar.setIconTextGap(10);
        btBuscar.setMargin(new java.awt.Insets(0, 20, 0, 20));
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
                menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                .addContainerGap(18, Short.MAX_VALUE)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btMostrarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24))
        );
        menuPanelLayout.setVerticalGroup(
                menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btMostrarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(397, Short.MAX_VALUE))
        );

        mainPanel.setBorder(new javax.swing.border.LineBorder(CustomColors.MAIN_COLOR.getColor(), 2, true));

        btSalir.setBackground(CustomColors.DANGER_RED.getColor());
        btSalir.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        btSalir.setIcon(UtilsGUI.getIcon(FontAwesome.TIMES_CIRCLE, 24
                , CustomColors.LIGHT_COLOR.getColor())
        );
        btSalir.setText(null);
        btSalir.setBorder(null);
        btSalir.setFocusable(false);
        btSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalir.setIconTextGap(0);
        btSalir.setMaximumSize(new java.awt.Dimension(30, 30));
        btSalir.setMinimumSize(new java.awt.Dimension(30, 30));
        btSalir.setPreferredSize(new java.awt.Dimension(30, 30));
        btSalir.setSize(new java.awt.Dimension(30, 30));
        btSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSalirMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSalirMouseExited(evt);
            }
        });
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout guiPanelLayout = new javax.swing.GroupLayout(guiPanel);
        guiPanel.setLayout(guiPanelLayout);
        guiPanelLayout.setHorizontalGroup(
                guiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(guiPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(guiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(guiPanelLayout.createSequentialGroup()
                                                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(guiPanelLayout.createSequentialGroup()
                                                .addComponent(mainTitleLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(guiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(11, Short.MAX_VALUE))
        );
        guiPanelLayout.setVerticalGroup(
                guiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiPanelLayout.createSequentialGroup()
                                .addGroup(guiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(guiPanelLayout.createSequentialGroup()
                                                .addComponent(mainTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(guiPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50))
        );

        menuBar.setBackground(CustomColors.MAIN_COLOR.getColor());
        menuBar.setForeground(CustomColors.DARK_COLOR.getColor());
        menuBar.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N

        archivoMenu.setForeground(CustomColors.DARK_COLOR.getColor());
        archivoMenu.setIcon(UtilsGUI.getIcon(FontAwesome.HOME, 18, CustomColors.DARK_COLOR.getColor())
        );
        archivoMenu.setText("Archivo");
        archivoMenu.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        archivoMenu.setIconTextGap(12);

        modoOscuroMenuItem.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        modoOscuroMenuItem.setForeground(CustomColors.DARK_COLOR.getColor());
        modoOscuroMenuItem.setText("Modo oscuro");
        modoOscuroMenuItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modoOscuroMenuItemItemStateChanged(evt);
            }
        });
        archivoMenu.add(modoOscuroMenuItem);

        salirMenuItem.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        salirMenuItem.setForeground(CustomColors.DARK_COLOR.getColor());
        salirMenuItem.setIcon(UtilsGUI.getIcon(FontAwesome.SIGN_OUT, 18, CustomColors.DARK_COLOR.getColor())
        );
        salirMenuItem.setText("Salir");
        salirMenuItem.setIconTextGap(10);
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        archivoMenu.add(salirMenuItem);

        menuBar.add(archivoMenu);

        reportesMenu.setForeground(CustomColors.DARK_COLOR.getColor());
        reportesMenu.setIcon(UtilsGUI.getIcon(FontAwesome.FILE_ARCHIVE_O, 18, CustomColors.DARK_COLOR.getColor())
        );
        reportesMenu.setText("Reportes");
        reportesMenu.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        reportesMenu.setIconTextGap(12);

        repListaCursoMenuItem.setFont(new java.awt.Font("Fira Sans", 0, 15)); // NOI18N
        repListaCursoMenuItem.setForeground(CustomColors.DARK_COLOR.getColor());
        repListaCursoMenuItem.setIcon(UtilsGUI.getIcon(FontAwesome.FILE_EXCEL_O, 18, CustomColors.DARK_COLOR.getColor())
        );
        repListaCursoMenuItem.setText("Lista de curso");
        repListaCursoMenuItem.setIconTextGap(10);
        repListaCursoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repListaCursoMenuItemActionPerformed(evt);
            }
        });
        reportesMenu.add(repListaCursoMenuItem);

        menuBar.add(reportesMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(guiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(guiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Permite agregar un alumno al sistema
     *
     * @param evt Evento
     */
    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        // TODO add your handling code here:
        this.mainPanel.setActualPanel(new AlumnoViewGUI(this.alumnoData, this.apoderadoData, this.cursosList, this.mainPanel), "Agregar alumno", "Seleccione el curso del alumno a agregar.");
    }//GEN-LAST:event_btAgregarActionPerformed

    /**
     * Permite mostrar la lista de un curso determinado.
     *
     * @param evt Evento.
     */
    private void btMostrarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarListaActionPerformed
        // TODO add your handling code here:
        this.mainPanel.setActualPanel(new MostrarViewGUI(this.cursosList, this.mainPanel), "Mostrar lista de curso",
                "Seleccione curso");
    }//GEN-LAST:event_btMostrarListaActionPerformed

    /**
     * Permite salir de la aplicación
     *
     * @param evt Evento
     */
    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        int opt = UtilsGUI.msjSiNo("¿Deseas salir de la aplicación?");
        if (opt == 0) System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    /**
     * Permite buscar una persona en el sistema.
     *
     * @param evt Evento.
     */
    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        this.mainPanel.setActualPanel(new BuscarViewGUI(this.alumnoData, this.apoderadoData, this.profesorData, this.mainPanel),
                "Buscar persona", "Ingrese RUT de persona a buscar");
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirMouseEntered

    private void btSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirMouseExited

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        // TODO add your handling code here:
        btSalirActionPerformed(evt);
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void repListaCursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repListaCursoMenuItemActionPerformed
        // TODO add your handling code here:
        JComboBox<String> comboBox = new JComboBox<>();
        comboBox.setModel(UtilsGUI.getCursosCB(this.cursosList));
        String msg = "Seleccione el curso a generar reporte";
        JFileChooser fileChooser = new JFileChooser();
        Object[] params = {msg, comboBox};
        if (JOptionPane.showConfirmDialog(null, params, "Seleccione curso",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            Curso curso = UtilsGUI.getCursoFromCB(comboBox, this.cursosList);
            fileChooser.showSaveDialog(null);
            System.out.println(fileChooser.getSelectedFile().getAbsolutePath());
            String filePath = ReportesControllerGUI.generarReporteListaCurso(curso);
            int abrirArchivo = JOptionPane.showConfirmDialog(null,
                    "El reporte se ha generado con éxito en " + filePath + ". Deseas " +
                            "abrir el archivo?", "Archivo " + "generado", JOptionPane.YES_NO_OPTION,
                    JOptionPane.INFORMATION_MESSAGE);
            if (abrirArchivo == JOptionPane.YES_OPTION) {
                try {
                    Desktop.getDesktop().open(new File(filePath));
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_repListaCursoMenuItemActionPerformed

    private void modoOscuroMenuItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modoOscuroMenuItemItemStateChanged
        // TODO add your handling code here:
        if (modoOscuroMenuItem.isSelected())
            this.darkMode = true;
        else
            this.darkMode = false;
        setColorMode();
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
    }//GEN-LAST:event_modoOscuroMenuItemItemStateChanged

    /**
     * Método main. Ejecuta la interfaz gráfica.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        
        try {
            GraphicsEnvironment ge = 
                GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("fonts/FiraSans.ttf")));
       } catch (IOException|FontFormatException e) {
            //Handle exception
            e.printStackTrace();
       }
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatArcOrangeIJTheme.setup();
        IconFontSwing.register(FontAwesome.getIconFont());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btMostrarLista;
    private javax.swing.JButton btSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel guiPanel;
    private aplicacion.views.gui.ShowPanelGUI mainPanel;
    private javax.swing.JLabel mainTitleLbl;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JCheckBoxMenuItem modoOscuroMenuItem;
    private javax.swing.JMenuItem repListaCursoMenuItem;
    private javax.swing.JMenu reportesMenu;
    private javax.swing.JMenuItem salirMenuItem;
    // End of variables declaration//GEN-END:variables
}
