/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplicacion.views.gui;

import aplicacion.controllers.gui.CustomColors;
import aplicacion.controllers.gui.UtilsGUI;
import jiconfont.icons.font_awesome.FontAwesome;

/**
 * Clase que controla la interacción con la pantalla de inicio en la ejecución de la interfaz gráfica.
 *
 * @author Sebastián García, Guillermo González, Benjamín Navarrete
 * @version 3.0
 */
public class InicioViewGUI extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public InicioViewGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(875, 480));
        setMinimumSize(new java.awt.Dimension(875, 480));
        setPreferredSize(new java.awt.Dimension(875, 480));
        setSize(new java.awt.Dimension(875, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jLabel1.setIcon(UtilsGUI.getIcon(FontAwesome.ARROW_CIRCLE_O_RIGHT, 25, CustomColors.DARK_COLOR.getColor())
        );
        jLabel1.setText("Obtener información");
        jLabel1.setIconTextGap(10);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(1);
        jTextArea1.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Bienvenidos al sistema de gestión de asistencia.  Estás en la pantalla de inicio. Esta herramienta \npermite gestionar la asistencia de los alumnos de un colegio durante un año escolar. Posee las \nherramientas necesarias para el control y gestión de cursos, alumnos, profesores y estudiantes.  \nAdemás, el programa nos permite:");
        jTextArea1.setToolTipText("");
        jTextArea1.setBorder(null);
        add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 820, 110));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
