/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplicacion.views.gui;

import aplicacion.controllers.gui.CustomColors;
import aplicacion.models.Alumno;
import aplicacion.models.Curso;
import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.awt.*;
import java.util.List;
import java.util.Map;

/**
 * Clase que controla la interacción con los cursos en la ejecución de la interfaz gráfica.
 *
 * @author Sebastián García, Guillermo González, Benjamín Navarrete
 * @version 4.0
 */
public class MostrarViewGUI extends javax.swing.JPanel {

    private final List<Curso> cursoData;
    private final ShowPanelGUI bg;

    /**
     * Creates new form Mostrar
     */
    public MostrarViewGUI(List<Curso> cursoData, ShowPanelGUI bg) {
        this.cursoData = cursoData;
        this.bg = bg;
        initComponents();
    }
    
    private DefaultComboBoxModel getCursosCB() {
        String labels[] = new String[this.cursoData.size()];
        int i = 0;
        for (Curso curso : this.cursoData) {
            labels[i] = curso.cursoToString();
            i++;
        }
        return new DefaultComboBoxModel(labels);
    }
    
    private Icon eyeIcon() {
        return IconFontSwing.buildIcon(FontAwesome.EYE, 18, new Color(250, 250, 250));
    }

    /**
     * Permite transformar un Map de alumnos a el formato que se necesita para mostrar por el JTable.
     *
     * @param alumnos HashMap con los alumnos
     * @return Matriz de Object con los alumnos.
     */
    private Object[][] alumnosATabla(Map<String, Alumno> alumnos) {
        Object[][] tabla = new Object[alumnos.size()][6];
        int i = 0;
        for (Map.Entry<String, Alumno> alumno: alumnos.entrySet()) {
            tabla[i][0] = alumno.getValue().getRut();
            tabla[i][1] = alumno.getValue().getNombres();
            tabla[i][2] = alumno.getValue().getApPaterno();
            tabla[i][3] = alumno.getValue().getApMaterno();
            tabla[i][4] = alumno.getValue().getApoderado().getNombreCompleto();
            tabla[i][5] = alumno.getValue().getApoderado().getTelefono();
            i++;
        }
        return tabla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(875, 480));
        setMinimumSize(new java.awt.Dimension(875, 480));
        setSize(new java.awt.Dimension(875, 480));

        jButton1.setBackground(CustomColors.MAIN_COLOR.getColor());
        jButton1.setFont(new java.awt.Font("Fira Sans", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(250, 250, 250));
        jButton1.setIcon(eyeIcon());
        jButton1.setText("Ver");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        jComboBox1.setModel(this.getCursosCB());
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jScrollPane1.setMaximumSize(new java.awt.Dimension(830, 385));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(830, 385));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(830, 385));
        jScrollPane1.setSize(new java.awt.Dimension(830, 385));

        jTable1.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null, null}
                },
                new String[]{
                        "RUT",
                        "Nombres",
                        "Ap. Paterno",
                        "Ap. Materno",
                        "Apoderado",
                        "Teléfono"
                }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(830, 385));
        jTable1.setMinimumSize(new java.awt.Dimension(830, 385));
        jTable1.setPreferredSize(new java.awt.Dimension(830, 385));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSize(new java.awt.Dimension(830, 385));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel1.setText("Seleccione el curso:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1)))
                                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Curso curso = null;
        for (Curso c : this.cursoData) {
            if (c != null && c.cursoToString().equals(jComboBox1.getSelectedItem().toString())) {
                curso = c;
            }
        }
        if (curso != null) {
            Curso finalCurso = curso;
            Object[][] tablaAlumnos = alumnosATabla(curso.getAlumnos());
            String[] titulos = new String[]{
                    "RUT",
                    "Nombres",
                    "Ap. Paterno",
                    "Ap. Materno",
                    "Apoderado",
                    "Teléfono"
            };
            jTable1.setModel(new AbstractTableModel() {
                @Override
                public int getRowCount() {
                    return finalCurso.getAlumnos().size();
                }

                @Override
                public int getColumnCount() {
                    return 6;
                }

                @Override
                public String getColumnName(int col) {
                    return titulos[col];
                }

                @Override
                public Object getValueAt(int row, int col) {
                    return tablaAlumnos[row][col];
                }
            });
        }
        this.bg.setSubtitle("Alumnos del " + jComboBox1.getSelectedItem().toString());


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        this.bg.setSubtitle("Curso seleccionado: " + jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
