/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplicacion.views.gui;

import aplicacion.controllers.gui.MessageUtilsGUI;
import aplicacion.data.CursoData;
import aplicacion.models.Alumno;
import aplicacion.models.Curso;
import java.awt.Color;
import java.util.List;

import javax.swing.table.AbstractTableModel;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.table.DefaultTableModel;

import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 * Clase que controla la interacción con los cursos en la ejecución de la interfaz gráfica.
 *
 * @author Sebastián García, Guillermo González, Benjamín Navarrete
 * @version 3.0
 */
public class MostrarViewGUI extends javax.swing.JPanel {

    private final CursoData cursoData;

    /**
     * Creates new form Mostrar
     */
    public MostrarViewGUI(CursoData cursoData) {
        this.cursoData = cursoData;
        initComponents();
        
    }
    
    private DefaultComboBoxModel getCursosCB() {
        
        List<Curso> cursos = this.cursoData.getCursos();
        String labels[] = new String[cursos.size()];
        int i = 0;
        for (Curso curso: cursos) {
            labels[i] = curso.cursoToString();
            i++;
        }
        return new DefaultComboBoxModel(labels);
    }
    
    private Icon eyeIcon() {
        return IconFontSwing.buildIcon(FontAwesome.EYE, 18, new Color(250, 250, 250));
    }

    /**
     * Permite transformar un Map de alumnos a el formato que se necesita para mostrar por el JTable.
     *
     * @param alumnos HashMap con los alumnos
     * @return Matriz de Object con los alumnos.
     */
    private Object[][] alumnosATabla(Map<String, Alumno> alumnos) {
        Object[][] tabla = new Object[alumnos.size()][6];
        int i = 0;
        for (Map.Entry<String, Alumno> alumno: alumnos.entrySet()) {
            tabla[i][0] = alumno.getValue().getRut();
            tabla[i][1] = alumno.getValue().getNombres();
            tabla[i][2] = alumno.getValue().getApPaterno();
            tabla[i][3] = alumno.getValue().getApMaterno();
            tabla[i][4] = alumno.getValue().getApoderado().getNombreCompleto();
            tabla[i][5] = alumno.getValue().getApoderado().getTelefono();
            i++;
        }
        return tabla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 239, 240));
        setForeground(new java.awt.Color(240, 239, 240));

        jButton1.setBackground(new java.awt.Color(0, 142, 153));
        jButton1.setFont(new java.awt.Font("Fira Sans", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(250, 250, 250));
        jButton1.setIcon(eyeIcon());
        jButton1.setText("Ver");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(250, 250, 250));
        jComboBox1.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(35, 33, 35));
        jComboBox1.setModel(this.getCursosCB());

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 142, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mostrar lista de curso");

        jLabel15.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 142, 153));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Seleccione el curso");

        jTable1.setBackground(new java.awt.Color(240, 239, 240));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String[]{
                "RUT",
                "Nombres",
                "Ap. Paterno",
                "Ap. Materno",
                "Apoderado",
                "Teléfono"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel16.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 142, 153));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Curso curso = null;
        for (Curso c: cursoData.getCursos()) {
            if (c != null && c.cursoToString().equals(jComboBox1.getSelectedItem().toString())) {
                curso = c;
            }
        }
        if (curso != null) {
            jLabel16.setText("Curso: " + curso.cursoToString());
            Curso finalCurso = curso;
            Object[][] tablaAlumnos = alumnosATabla(curso.getAlumnos());
            String[] titulos = new String[]{
                    "RUT",
                    "Nombres",
                    "Ap. Paterno",
                    "Ap. Materno",
                    "Apoderado",
                    "Teléfono"
            };
            jTable1.setModel(new AbstractTableModel() {
                @Override
                public int getRowCount() {
                    return finalCurso.getAlumnos().size();
                }

                @Override
                public int getColumnCount() {
                    return 6;
                }

                @Override
                public String getColumnName(int col) {
                    return titulos[col];
                }

                @Override
                public Object getValueAt(int row, int col) {
                    return tablaAlumnos[row][col];
                }
            });
        }
        

        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
