/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplicacion.views.gui;

import aplicacion.controllers.gui.CustomColors;

import javax.swing.*;

/**
 * Clase que controla la interacción con la pantalla de inicio en la ejecución de la interfaz gráfica.
 *
 * @author Sebastián García, Guillermo González, Benjamín Navarrete
 * @version 3.0
 */
public class ShowPanelGUI extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public ShowPanelGUI() {
        initComponents();
    }

    /**
     * Método que establece el título del panel de la interfaz gráfica
     *
     * @param title Nombre del título a mostrar
     */
    public void setTitle(String title) {
        this.titleLbl.setText(title);
    }

    /**
     * Método que establece el subtítulo del panel de la interfaz gráfica
     *
     * @param subtitle Nombre del subtítulo a mostrar
     */
    public void setSubtitle(String subtitle) {
        this.subtitleLbl.setText(subtitle);
    }

    /**
     * Método que establece un panel en pantalla
     *
     * @param newPanel Parámetro para inicializar el panel
     * @param title Título principal que tendrá el Panel
     */
    public void setActualPanel(JPanel newPanel, String title) {
        setTitle(title);
        setSubtitle("");
        newPanel.setSize(873, 573);
        newPanel.setLocation(0, 0);
        this.jPanel1.removeAll();
        this.jPanel1.add(newPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 0, 490));
        this.jPanel1.revalidate();
        this.jPanel1.repaint();
    }

    /**
     * Método que establece un panel en pantalla
     *
     * @param newPanel Parámetro para inicializar el panel
     * @param title Título principal que tendrá el Panel
     * @param subtitle Subtitulo que tendrá el panel
     */
    public void setActualPanel(JPanel newPanel, String title, String subtitle) {
        setTitle(title);
        setSubtitle(subtitle);
        newPanel.setSize(873, 573);
        newPanel.setLocation(0, 0);
        this.jPanel1.removeAll();
        this.jPanel1.add(newPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 0, 490));
        this.jPanel1.revalidate();
        this.jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        subtitleLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBorder(new javax.swing.border.LineBorder(CustomColors.MAIN_COLOR.getColor(), 2, true));
        setMaximumSize(new java.awt.Dimension(875, 575));
        setMinimumSize(new java.awt.Dimension(875, 575));
        setPreferredSize(new java.awt.Dimension(875, 575));
        setSize(new java.awt.Dimension(875, 575));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("Fira Sans", 1, 28)); // NOI18N
        titleLbl.setText("Bienvenido");
        add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 830, -1));

        subtitleLbl.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        subtitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subtitleLbl.setText("Subtítulo");
        add(subtitleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 820, -1));

        jPanel1.setLocation(new java.awt.Point(2, 2));
        jPanel1.setMaximumSize(new java.awt.Dimension(871, 476));
        jPanel1.setMinimumSize(new java.awt.Dimension(871, 476));
        jPanel1.setPreferredSize(new java.awt.Dimension(871, 476));
        jPanel1.setSize(new java.awt.Dimension(871, 476));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 871, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 476, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 97, 871, 476));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel subtitleLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
